# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    resolvers:
        default:
            web_path:
                web_root: ~ %kernel.project_dir%/public
                cache_prefix: ~ media/

    loaders:
        default:
            filesystem:
                data_root: ~ %kernel.project_dir%/public

    filter_sets:
        cache: ~
        thumb_mini:
            quality: 75
            filters:
                thumbnail: { size: [ 40 , 40], mode: outbound }
        thumb:
            quality: 75
            filters:
                thumbnail: { size: [ 180 , 180], mode: outbound }
        thumb_big:
            quality: 75
            filters:
                thumbnail: { size: [ 400 , 400], mode: outbound }
